### ISSUE TITLE
Config reset on startup!

### ISSUE THREAD

**Issue by kkHubq4xvMC6Tjhkg0jtTSBbeZ6REYL7SFvB** [obzidi4n/delphivote#1]
In version 1.1, the config files reset on every startup!

(sorry for my bad english)

Cool plugin btw. (zhe only really simple vote listener)

**Comment by obzidi4n** [comment]
Thanks for the alert -- let me test that.   The plugin should only be updating essential elements of the config files in case they are missing --

**Comment by kkHubq4xvMC6Tjhkg0jtTSBbeZ6REYL7SFvB** [comment]
Most times, the config files reset to the previous version on startup for some reason
also in v 1.0
Some times, it works fine

**Comment by kkHubq4xvMC6Tjhkg0jtTSBbeZ6REYL7SFvB** [comment]
on reload too

**Comment by obzidi4n** [comment]
Thanks again for the heads-up.   Try the new 1.2 version, issue should be fixed!

https://github.com/obzidi4n/delphivote/releases/tag/version-1.2

**Comment by kkHubq4xvMC6Tjhkg0jtTSBbeZ6REYL7SFvB** [comment]
Still not working for some reason.

**Comment by obzidi4n** [comment]
Sorry about that.  Could you test the 1.2 version once more?  Be sure to delete the entire plugins/DelphiVote folder first, and let the files auto-generate when you reboot.   You should be able to modify those new files without losing any changes you make.

**Comment by kkHubq4xvMC6Tjhkg0jtTSBbeZ6REYL7SFvB** [comment]
cant reproduce this with 1.2
sorry
false alert

**Comment by obzidi4n** [comment]
Awesome -- thanks for the update!
